### ISSUE TITLE
Upstream issue with systemd where rpcbind_service enable keeps changing from false to true.

### ISSUE THREAD

**Issue by benkevan** [ghoneycutt/puppet-module-rpcbind#27]
Every run will contain: 
Notice: /Stage[main]/Rpcbind/Service[rpcbind_service]/enable: enable changed 'false' to 'true'

Although it's enabled, the is-enabled output isn't "enabled"
systemctl status rpcbind
● rpcbind.service - RPC bind service
   Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; indirect; vendor preset: enabled)
   Active: active (running) since Tue 2017-09-05 19:01:39 UTC; 2 weeks 5 days ago
 Main PID: 1683 (rpcbind)
   CGroup: /system.slice/rpcbind.service
           └─1683 /sbin/rpcbind -w

systemctl is-enabled rpcbind.service; echo $?
indirect
0

Changes in puppet 4.9 moved the default of is-enable for indirect to false (even with an exit status of 0).

**Comment by ghoneycutt** [comment]
I don't understand what needs to happen. What OS platform and version(s) of Puppet are you using?

**Comment by benkevan** [comment]
The original change to behavior of indirect systemd states were a part of: 
https://tickets.puppetlabs.com/browse/PUP-6759

Now others have reported that they want more granular output for systemd: 
https://tickets.puppetlabs.com/browse/PUP-7163

and even cleanup upstream for systemd: 
https://github.com/systemd/systemd/issues/6681

I think it's much more of an upstream issue, I can get around it by doing enabled => false,. Because indirect had been made considered as "disabled". 

I'm running puppet 4.11 on CentOS 7

More of an FYI and tracker for this specific module as it's impacted by this behavior.

I may, however, just throw in a quick if statement around the output of systemctl is-enabled as a quick dirty fix.

**Comment by ghoneycutt** [comment]
Thanks @benkevan

**Comment by ghoneycutt** [comment]
Not seeing this behavior with the new v2 of this module using EL7.

Thank you for documenting your work around.
